### ISSUE TITLE
Double Language / xx.BluRay

### ISSUE THREAD

**Issue by docgonzo2015** [scttcper/video-filename-parser#63]
Hi!

Can u check if a release is DL / ML (Multilanguage)?
Also the Country, where the bluray comes from isnt checked.

`Sophie.Scholl.Die.letzten.Tage.2005.German.AC3.DL.1080p.UK.BluRay.x264-dOc`

**Comment by scttcper** [comment]
Added parsing DL as a MULTI/DUAL release. Not going to add country parsing as its not something that scene releases have and pretty use case specific
