### ISSUE TITLE
Import problem with react native

### ISSUE THREAD

**Issue by aldobel** [scttcper/video-filename-parser#66]
Slave everyone, I'm trying to use this library with react native, but on import, it gives me an error:
```
While trying to resolve module `@ctrl/video-filename-parser` from file `myDirFile.js`,
the package `Dir/node_modules/@ctrl/video-filename-parser/package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved 
(`myDir/node_modules/@ctrl/video-filename-parser/index`. Indeed, none of these files exist:
```
I tried adding to the package.json file:
```
'main': './dist/src/index.js'
```
without success.
How can I solve this problem? thank you

**Comment by scttcper** [comment]
so the package is now pure esm https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

You could try using an older version [3.7.0](https://github.com/scttcper/video-filename-parser/releases/tag/v3.7.0) or figuring out how to import and ESM module with your webpack/native setup.
